### ISSUE TITLE
go get github.com/mndrix/golog/bin fails

### ISSUE THREAD

**Issue by mehlon** [mndrix/golog#20]
Executing `go get github.com/mndrix/golog/bin` gives: `imported and not used: "github.com/mndrix/ps"`.

Also, it should probably be moved to `github.com/mndrix/golog/cmd/golog` so that the binary would be called 'golog', not 'bin'.

**Comment by mndrix** [comment]
One can now install golog with "go get github.com/mndrix/golog/cmd/golog" or "go get github.com/mndrix/golog/..."
