### ISSUE TITLE
Use type assertions instead of reflect.

### ISSUE THREAD

**Issue by EricLagergren** [mndrix/golog#21]
[This line](https://github.com/mndrix/golog/blob/master/read/read.go#L80) can be simplified down to:

```
if r, ok := src.(io.Reader); {
    return r, nil
}
````

Testing it locally, this change added a 2x speedup (4.91671ms -> 2.944214ms) for creating a NewMachine. Additionally, this drops the need to include the reflection library.

**Comment by EricLagergren** [comment]
Additionally, a `[]byte` case could be added that returns `bytes.NewReader(x), nil` to handle []byte for no additional cost.

**Comment by mndrix** [comment]
Please submit pull requests for code improvements. Golog was one of my first Go projects, so there's a lot of room for similar changes. I'm glad to consider them all.
